import type { FoodDefinition } from "./food-calories-types";

/** 일반적인 1회 제공량 기준 칼로리 (식품성분표·영양 정보 평균값 참고) */
export const FOOD_DATABASE: FoodDefinition[] = [
  // ── 단백질 · 고기 · 생선 ──
  { name: "닭가슴살", aliases: ["닭 가슴살", "치킨브레스트"], servingLabel: "100g", caloriesPerServing: 165 },
  { name: "닭다리", aliases: ["닭다리살", "치킨다리"], servingLabel: "1개(100g)", caloriesPerServing: 210 },
  { name: "닭갈비", aliases: ["양념치킨", "후라이드치킨"], servingLabel: "100g", caloriesPerServing: 250 },
  { name: "삼겹살", aliases: ["돼지삼겹", "구이삼겹"], servingLabel: "100g", caloriesPerServing: 330 },
  { name: "목살", aliases: ["돼지목살"], servingLabel: "100g", caloriesPerServing: 280 },
  { name: "돼지고기", aliases: ["돼지고기볶음"], servingLabel: "100g", caloriesPerServing: 250 },
  { name: "소고기", aliases: ["소고기구이"], servingLabel: "100g", caloriesPerServing: 250 },
  { name: "소고기등심", aliases: ["등심", "스테이크"], servingLabel: "100g", caloriesPerServing: 270 },
  { name: "소고기안심", aliases: ["안심"], servingLabel: "100g", caloriesPerServing: 200 },
  { name: "불고기", aliases: ["소불고기"], servingLabel: "1인분(150g)", caloriesPerServing: 350 },
  { name: "갈비", aliases: ["LA갈비", "양념갈비"], servingLabel: "100g", caloriesPerServing: 320 },
  { name: "제육볶음", aliases: ["제육"], servingLabel: "1인분(200g)", caloriesPerServing: 450 },
  { name: "수육", aliases: ["보쌈", "보쌈수육"], servingLabel: "1인분(150g)", caloriesPerServing: 380 },
  { name: "족발", aliases: ["편육"], servingLabel: "100g", caloriesPerServing: 230 },
  { name: "연어", aliases: ["연어구이", "훈제연어", "연어회"], servingLabel: "100g", caloriesPerServing: 206 },
  { name: "고등어", aliases: ["고등어구이", "고등어조림"], servingLabel: "1토막(100g)", caloriesPerServing: 230 },
  { name: "참치", aliases: ["참치회", "참치캔"], servingLabel: "100g", caloriesPerServing: 130 },
  { name: "참치캔", aliases: ["참치통조림", "캔참치"], servingLabel: "1/2캔(75g)", caloriesPerServing: 90 },
  { name: "새우", aliases: ["왕새우", "새우구이"], servingLabel: "5마리(80g)", caloriesPerServing: 85 },
  { name: "오징어", aliases: ["오징어볶음", "오징어회"], servingLabel: "100g", caloriesPerServing: 92 },
  { name: "문어", aliases: ["문어숙회"], servingLabel: "100g", caloriesPerServing: 82 },
  { name: "조개", aliases: ["바지락", "홍합"], servingLabel: "100g", caloriesPerServing: 75 },
  { name: "계란", aliases: ["달걀", "삶은계란", "계란후라이"], servingLabel: "1개(50g)", caloriesPerServing: 78 },
  { name: "두부", aliases: ["연두부", "찌개두부", "부침두부"], servingLabel: "1/2모(150g)", caloriesPerServing: 120 },
  { name: "햄", aliases: ["슬라이스햄"], servingLabel: "2장(40g)", caloriesPerServing: 60 },
  { name: "베이컨", aliases: ["베컨"], servingLabel: "2장(30g)", caloriesPerServing: 90 },
  { name: "소시지", aliases: ["프랑크"], servingLabel: "1개(50g)", caloriesPerServing: 150 },
  { name: "프로틴쉐이크", aliases: ["프로틴", "단백질쉐이크"], servingLabel: "1스쿱(30g)", caloriesPerServing: 120 },

  // ── 밥 · 면 · 빵 ──
  { name: "현미밥", aliases: ["현미", "현미밥공기"], servingLabel: "1공기(210g)", caloriesPerServing: 310 },
  { name: "백미밥", aliases: ["흰밥", "쌀밥", "밥공기"], servingLabel: "1공기(210g)", caloriesPerServing: 300 },
  { name: "볶음밥", aliases: ["계란볶음밥", "새우볶음밥"], servingLabel: "1그릇", caloriesPerServing: 450 },
  { name: "김치볶음밥", aliases: ["김치덮밥"], servingLabel: "1그릇", caloriesPerServing: 480 },
  { name: "비빔밥", aliases: ["전주비빔밥"], servingLabel: "1그릇", caloriesPerServing: 550 },
  { name: "덮밥", aliases: ["규동", "가츠동"], servingLabel: "1그릇", caloriesPerServing: 650 },
  { name: "카레라이스", aliases: ["카레", "일본카레"], servingLabel: "1그릇", caloriesPerServing: 600 },
  { name: "오트밀", aliases: ["귀리", "오트밀죽"], servingLabel: "1그릇(40g)", caloriesPerServing: 150 },
  { name: "라면", aliases: ["즉석라면", "컵라면", "신라면"], servingLabel: "1봉", caloriesPerServing: 500 },
  { name: "우동", aliases: ["가락우동"], servingLabel: "1그릇", caloriesPerServing: 350 },
  { name: "소바", aliases: ["메밀소바", "냉소바"], servingLabel: "1그릇", caloriesPerServing: 330 },
  { name: "국수", aliases: ["잔치국수", "메밀국수"], servingLabel: "1그릇", caloriesPerServing: 380 },
  { name: "칼국수", aliases: ["해물칼국수"], servingLabel: "1그릇", caloriesPerServing: 450 },
  { name: "냉면", aliases: ["물냉면", "비빔냉면", "평양냉면"], servingLabel: "1그릇", caloriesPerServing: 480 },
  { name: "짜장면", aliases: ["간짜장", "삼선짜장"], servingLabel: "1그릇", caloriesPerServing: 650 },
  { name: "짬뽕", aliases: ["해물짬뽕", "삼선짬뽕"], servingLabel: "1그릇", caloriesPerServing: 600 },
  { name: "파스타", aliases: ["스파게티", "크림파스타", "토마토파스타"], servingLabel: "1인분(250g)", caloriesPerServing: 550 },
  { name: "빵", aliases: ["식빵", "토스트"], servingLabel: "1장(30g)", caloriesPerServing: 80 },
  { name: "통밀빵", aliases: ["홀그레인"], servingLabel: "1장(35g)", caloriesPerServing: 85 },
  { name: "크로와상", aliases: ["croissant"], servingLabel: "1개(60g)", caloriesPerServing: 270 },
  { name: "베이글", aliases: ["플레인베이글"], servingLabel: "1개(100g)", caloriesPerServing: 280 },
  { name: "김밥", aliases: ["참치김밥", "야채김밥", "치즈김밥"], servingLabel: "1줄", caloriesPerServing: 350 },
  { name: "주먹밥", aliases: ["삼각김밥", "onigiri"], servingLabel: "1개", caloriesPerServing: 180 },
  { name: "떡", aliases: ["백설기", "가래떡", "인절미"], servingLabel: "1개(50g)", caloriesPerServing: 110 },
  { name: "떡볶이", aliases: ["국물떡볶이", "로제떡볶이"], servingLabel: "1인분(300g)", caloriesPerServing: 400 },
  { name: "만두", aliases: ["군만두", "찐만두", "물만두"], servingLabel: "5개", caloriesPerServing: 250 },
  { name: "교자", aliases: ["왕교자", "물교자"], servingLabel: "5개", caloriesPerServing: 280 },

  // ── 초밥 · 일식 ──
  { name: "연어초밥", aliases: ["연어스시", "연어한조각"], servingLabel: "2피스", caloriesPerServing: 100 },
  { name: "참치초밥", aliases: ["참치스시", "참치한조각"], servingLabel: "2피스", caloriesPerServing: 90 },
  { name: "새우초밥", aliases: ["새우스시"], servingLabel: "2피스", caloriesPerServing: 80 },
  { name: "장어초밥", aliases: ["장어스시", "장어"], servingLabel: "2피스", caloriesPerServing: 180 },
  { name: "계란초밥", aliases: ["계란말이초밥", "tamago"], servingLabel: "2피스", caloriesPerServing: 120 },
  { name: "초밥세트", aliases: ["스시세트", "모듬초밥"], servingLabel: "10피스", caloriesPerServing: 450 },
  { name: "회덮밥", aliases: ["사시미덮밥", "연어덮밥"], servingLabel: "1그릇", caloriesPerServing: 550 },
  { name: "사시미", aliases: ["모듬회", "회"], servingLabel: "1인분(150g)", caloriesPerServing: 200 },
  { name: "라멘", aliases: ["돈코츠라멘", "미소라멘", "쇼유라멘"], servingLabel: "1그릇", caloriesPerServing: 550 },
  { name: "돈까스", aliases: ["돈카츠", "치즈돈까스"], servingLabel: "1인분", caloriesPerServing: 650 },
  { name: "가츠동", aliases: ["돈까스덮밥"], servingLabel: "1그릇", caloriesPerServing: 700 },
  { name: "텐동", aliases: ["새우튀김덮밥"], servingLabel: "1그릇", caloriesPerServing: 650 },
  { name: "텐푸라", aliases: ["튀김", "새우튀김"], servingLabel: "5개", caloriesPerServing: 280 },
  { name: "타코야키", aliases: ["문어빵"], servingLabel: "6개", caloriesPerServing: 300 },
  { name: "오코노미야키", aliases: ["오코노미"], servingLabel: "1장", caloriesPerServing: 450 },
  { name: "낫또", aliases: ["natto"], servingLabel: "1팩(50g)", caloriesPerServing: 90 },
  { name: "미소국", aliases: ["된장국"], servingLabel: "1그릇", caloriesPerServing: 40 },

  // ── 샤브샤브 · 전골 · 찌개 ──
  { name: "샤브샤브", aliases: ["샤브", "중국샤브"], servingLabel: "1인분(고기+야채)", caloriesPerServing: 350 },
  { name: "소고기샤브", aliases: ["한우샤브"], servingLabel: "1인분", caloriesPerServing: 400 },
  { name: "버섯샤브", aliases: ["버섯전골"], servingLabel: "1인분", caloriesPerServing: 200 },
  { name: "전골", aliases: ["해물전골", "버섯전골"], servingLabel: "1인분", caloriesPerServing: 300 },
  { name: "부대찌개", aliases: ["부대찌"], servingLabel: "1그릇", caloriesPerServing: 450 },
  { name: "김치찌개", aliases: ["김치찌"], servingLabel: "1그릇(300g)", caloriesPerServing: 220 },
  { name: "된장찌개", aliases: ["된장찌"], servingLabel: "1그릇(300g)", caloriesPerServing: 180 },
  { name: "순두부찌개", aliases: ["순두부"], servingLabel: "1그릇", caloriesPerServing: 200 },
  { name: "청국장", aliases: ["청국장찌개"], servingLabel: "1그릇", caloriesPerServing: 150 },
  { name: "감자탕", aliases: ["뼈해장국"], servingLabel: "1그릇", caloriesPerServing: 400 },
  { name: "설렁탕", aliases: ["곰탕"], servingLabel: "1그릇", caloriesPerServing: 350 },
  { name: "육개장", aliases: ["육개"], servingLabel: "1그릇", caloriesPerServing: 300 },
  { name: "닭볶음탕", aliases: ["닭도리탕"], servingLabel: "1인분", caloriesPerServing: 400 },
  { name: "찜닭", aliases: ["안동찜닭"], servingLabel: "1인분", caloriesPerServing: 450 },
  { name: "삼계탕", aliases: ["삼계"], servingLabel: "1그릇", caloriesPerServing: 600 },
  { name: "미역국", aliases: ["미역국밥"], servingLabel: "1그릇", caloriesPerServing: 80 },
  { name: "떡국", aliases: ["떡만두국"], servingLabel: "1그릇", caloriesPerServing: 350 },
  { name: "어묵탕", aliases: ["오뎅탕", "오뎅"], servingLabel: "1그릇", caloriesPerServing: 200 },

  // ── 과일 ──
  { name: "사과", aliases: ["홍로", "부사"], servingLabel: "1개(200g)", caloriesPerServing: 104 },
  { name: "바나나", aliases: ["바나나1개"], servingLabel: "1개(120g)", caloriesPerServing: 105 },
  { name: "방울토마토", aliases: ["방울 토마토", "체리토마토"], servingLabel: "10개(100g)", caloriesPerServing: 18 },
  { name: "토마토", aliases: ["대토마토"], servingLabel: "1개(150g)", caloriesPerServing: 27 },
  { name: "오렌지", aliases: ["귤", "감귤", "한라봉"], servingLabel: "1개(130g)", caloriesPerServing: 60 },
  { name: "포도", aliases: ["캠벨포도", "샤인머스캣"], servingLabel: "1송이(150g)", caloriesPerServing: 105 },
  { name: "딸기", aliases: ["strawberry"], servingLabel: "10개(150g)", caloriesPerServing: 48 },
  { name: "블루베리", aliases: ["blueberry"], servingLabel: "1컵(150g)", caloriesPerServing: 85 },
  { name: "수박", aliases: ["watermelon"], servingLabel: "1조각(300g)", caloriesPerServing: 90 },
  { name: "멜론", aliases: ["캔멜론", "허니듀"], servingLabel: "1조각(200g)", caloriesPerServing: 68 },
  { name: "복숭아", aliases: ["천도복숭아"], servingLabel: "1개(150g)", caloriesPerServing: 60 },
  { name: "배", aliases: ["배1개"], servingLabel: "1개(250g)", caloriesPerServing: 115 },
  { name: "키위", aliases: ["kiwi", "골드키위"], servingLabel: "1개(80g)", caloriesPerServing: 50 },
  { name: "망고", aliases: ["mango"], servingLabel: "1개(200g)", caloriesPerServing: 135 },
  { name: "파인애플", aliases: ["pineapple"], servingLabel: "1컵(165g)", caloriesPerServing: 82 },
  { name: "체리", aliases: ["cherry"], servingLabel: "10개(80g)", caloriesPerServing: 50 },
  { name: "자두", aliases: ["plum"], servingLabel: "2개(100g)", caloriesPerServing: 46 },
  { name: "감", aliases: ["단감", "홍시"], servingLabel: "1개(150g)", caloriesPerServing: 80 },
  { name: "용과", aliases: ["dragonfruit"], servingLabel: "1/2개(100g)", caloriesPerServing: 60 },
  { name: "아보카도", aliases: ["avocado"], servingLabel: "1/2개(100g)", caloriesPerServing: 160 },
  { name: "레몬", aliases: ["lemon"], servingLabel: "1개(60g)", caloriesPerServing: 17 },
  { name: "석류", aliases: ["pomegranate"], servingLabel: "1/2컵(90g)", caloriesPerServing: 72 },
  { name: "무화과", aliases: ["fig"], servingLabel: "2개(100g)", caloriesPerServing: 74 },
  { name: "참외", aliases: ["koreanmelon"], servingLabel: "1/2개(150g)", caloriesPerServing: 25 },

  // ── 채소 · 샐러드 ──
  { name: "샐러드", aliases: ["야채샐러드", "그린샐러드", "시저샐러드"], servingLabel: "1접시(150g)", caloriesPerServing: 80 },
  { name: "브로콜리", aliases: ["broccoli"], servingLabel: "1컵(100g)", caloriesPerServing: 35 },
  { name: "시금치", aliases: ["시금치나물"], servingLabel: "1접시(100g)", caloriesPerServing: 25 },
  { name: "감자", aliases: ["찐감자", "군감자"], servingLabel: "1개(150g)", caloriesPerServing: 130 },
  { name: "고구마", aliases: ["군고구마", "찐고구마"], servingLabel: "1개(200g)", caloriesPerServing: 258 },
  { name: "당근", aliases: ["carrot"], servingLabel: "1개(60g)", caloriesPerServing: 25 },
  { name: "옥수수", aliases: ["찰옥수수", "콘"], servingLabel: "1개(100g)", caloriesPerServing: 90 },
  { name: "김치", aliases: ["배추김치", "깍두기"], servingLabel: "1접시(50g)", caloriesPerServing: 15 },
  { name: "나물", aliases: ["나물반찬", "3색나물"], servingLabel: "1접시(80g)", caloriesPerServing: 60 },

  // ── 디저트 · 간식 ──
  { name: "케이크", aliases: ["생크림케이크", "초코케이크"], servingLabel: "1조각(100g)", caloriesPerServing: 350 },
  { name: "치즈케이크", aliases: ["뉴욕치즈케이크"], servingLabel: "1조각(120g)", caloriesPerServing: 400 },
  { name: "티라미수", aliases: ["tiramisu"], servingLabel: "1조각(100g)", caloriesPerServing: 380 },
  { name: "마카롱", aliases: ["macaron"], servingLabel: "2개", caloriesPerServing: 140 },
  { name: "쿠키", aliases: ["초코칩쿠키", "버터쿠키"], servingLabel: "2개(30g)", caloriesPerServing: 150 },
  { name: "도넛", aliases: ["글레이즈드도넛", "doughnut"], servingLabel: "1개(60g)", caloriesPerServing: 260 },
  { name: "와플", aliases: ["waffle"], servingLabel: "1개(80g)", caloriesPerServing: 290 },
  { name: "팬케이크", aliases: ["pancake", "핫케이크"], servingLabel: "2장", caloriesPerServing: 200 },
  { name: "아이스크림", aliases: ["icecream", "바닐라아이스크림"], servingLabel: "1스쿱(100g)", caloriesPerServing: 200 },
  { name: "젤라또", aliases: ["gelato"], servingLabel: "1스쿱(80g)", caloriesPerServing: 160 },
  { name: "푸딩", aliases: ["pudding", "커스터드푸딩"], servingLabel: "1컵(120g)", caloriesPerServing: 180 },
  { name: "초콜릿", aliases: ["chocolate", "다크초콜릿", "밀크초콜릿"], servingLabel: "1판(30g)", caloriesPerServing: 160 },
  { name: "붕어빵", aliases: ["잉어빵"], servingLabel: "2마리", caloriesPerServing: 200 },
  { name: "호떡", aliases: ["hotteok"], servingLabel: "1개", caloriesPerServing: 250 },
  { name: "타르트", aliases: ["에그타르트", "과일타르트"], servingLabel: "1개", caloriesPerServing: 220 },
  { name: "크레페", aliases: ["crepe"], servingLabel: "1개", caloriesPerServing: 280 },
  { name: "브라우니", aliases: ["brownie"], servingLabel: "1조각(50g)", caloriesPerServing: 230 },
  { name: "마들렌", aliases: ["madeleine"], servingLabel: "2개", caloriesPerServing: 180 },
  { name: "팥빙수", aliases: ["빙수", "patbingsu"], servingLabel: "1그릇", caloriesPerServing: 450 },
  { name: "과일빙수", aliases: ["망고빙수"], servingLabel: "1그릇", caloriesPerServing: 400 },
  { name: "약과", aliases: ["yakgwa"], servingLabel: "2개", caloriesPerServing: 200 },
  { name: "한과", aliases: ["유과"], servingLabel: "2개", caloriesPerServing: 180 },
  { name: "식혜", aliases: ["sikhye"], servingLabel: "1컵(250ml)", caloriesPerServing: 120 },
  { name: "수정과", aliases: ["sujeonggwa"], servingLabel: "1컵(250ml)", caloriesPerServing: 100 },
  { name: "팥죽", aliases: ["단팥죽"], servingLabel: "1그릇", caloriesPerServing: 250 },
  { name: "호두과자", aliases: ["호두과자1개"], servingLabel: "1개", caloriesPerServing: 120 },
  { name: "카스테라", aliases: ["castella"], servingLabel: "1조각(50g)", caloriesPerServing: 160 },
  { name: "롤케이크", aliases: ["swissroll"], servingLabel: "1조각(40g)", caloriesPerServing: 140 },
  { name: "스콘", aliases: ["scone"], servingLabel: "1개(60g)", caloriesPerServing: 240 },
  { name: "머핀", aliases: ["muffin", "블루베리머핀"], servingLabel: "1개(80g)", caloriesPerServing: 320 },
  { name: "프레첼", aliases: ["pretzel", "프레즐"], servingLabel: "1개(60g)", caloriesPerServing: 230 },
  { name: "팝콘", aliases: ["popcorn", "버터팝콘"], servingLabel: "1봉(30g)", caloriesPerServing: 150 },
  { name: "감자칩", aliases: ["포테이토칩", "chips"], servingLabel: "1봉(30g)", caloriesPerServing: 160 },
  { name: "견과류", aliases: ["아몬드", "호두", "캐슈넛", "혼합견과"], servingLabel: "30g", caloriesPerServing: 180 },
  { name: "땅콩", aliases: ["peanut", "볶음땅콩"], servingLabel: "30g", caloriesPerServing: 170 },
  { name: "땅콩버터", aliases: ["피넛버터", "peanutbutter"], servingLabel: "1큰술(15g)", caloriesPerServing: 95 },

  // ── 양식 · 패스트푸드 ──
  { name: "피자", aliases: ["pizza", "페퍼로니피자", "치즈피자"], servingLabel: "1조각", caloriesPerServing: 280 },
  { name: "햄버거", aliases: ["burger", "치즈버거", "빅맥"], servingLabel: "1개", caloriesPerServing: 550 },
  { name: "감자튀김", aliases: ["frenchfries", "프렌치프라이"], servingLabel: "중(100g)", caloriesPerServing: 320 },
  { name: "치킨너겟", aliases: ["nugget", "맥너겟"], servingLabel: "6조각", caloriesPerServing: 280 },
  { name: "핫도그", aliases: ["hotdog"], servingLabel: "1개", caloriesPerServing: 300 },
  { name: "샌드위치", aliases: ["sandwich", "햄치즈샌드"], servingLabel: "1개", caloriesPerServing: 350 },
  { name: "치즈", aliases: ["슬라이스치즈", "체다치즈", "모짜렐라"], servingLabel: "1장(20g)", caloriesPerServing: 70 },

  // ── 음료 ──
  { name: "우유", aliases: ["저지방우유", "흰우유"], servingLabel: "1컵(200ml)", caloriesPerServing: 130 },
  { name: "두유", aliases: ["soymilk", "검은콩두유"], servingLabel: "1팩(190ml)", caloriesPerServing: 90 },
  { name: "그릭요거트", aliases: ["그릭요거트", "플레인요거트"], servingLabel: "1컵(170g)", caloriesPerServing: 100 },
  { name: "요거트", aliases: ["yogurt", "딸기요거트"], servingLabel: "1컵(150g)", caloriesPerServing: 120 },
  { name: "아메리카노", aliases: ["커피", "블랙커피", "americano"], servingLabel: "1잔", caloriesPerServing: 5 },
  { name: "카페라떼", aliases: ["라떼", "caffelatte"], servingLabel: "1잔", caloriesPerServing: 180 },
  { name: "카푸치노", aliases: ["cappuccino"], servingLabel: "1잔", caloriesPerServing: 120 },
  { name: "바닐라라떼", aliases: ["vanillalatte"], servingLabel: "1잔", caloriesPerServing: 250 },
  { name: "녹차", aliases: ["그린티", "greentea"], servingLabel: "1잔", caloriesPerServing: 2 },
  { name: "밀크티", aliases: ["milktea", "버블티", "타로"], servingLabel: "1잔(500ml)", caloriesPerServing: 350 },
  { name: "스무디", aliases: ["smoothie", "과일스무디"], servingLabel: "1잔(400ml)", caloriesPerServing: 280 },
  { name: "주스", aliases: ["오렌지주스", "사과주스", "juice"], servingLabel: "1컵(200ml)", caloriesPerServing: 110 },
  { name: "콜라", aliases: ["코카콜라", "pepsi", "탄산음료"], servingLabel: "1캔(355ml)", caloriesPerServing: 140 },
  { name: "제로콜라", aliases: ["zero콜라", "제로탄산"], servingLabel: "1캔(355ml)", caloriesPerServing: 0 },
  { name: "이온음료", aliases: ["포카리", "게토레이", "스포츠음료"], servingLabel: "1병(500ml)", caloriesPerServing: 120 },
  { name: "에너지드링크", aliases: ["에너지음료", "redbull"], servingLabel: "1캔(250ml)", caloriesPerServing: 110 },
  { name: "맥주", aliases: ["beer", "생맥주"], servingLabel: "1잔(500ml)", caloriesPerServing: 200 },
  { name: "소주", aliases: ["soju"], servingLabel: "1잔(50ml)", caloriesPerServing: 65 },
  { name: "와인", aliases: ["wine"], servingLabel: "1잔(150ml)", caloriesPerServing: 125 },
];
