-- AlterEnum
ALTER TYPE "CardioType" ADD VALUE 'TRACKING';
ALTER TYPE "CardioType" ADD VALUE 'HIKING';
ALTER TYPE "CardioType" ADD VALUE 'SPINNING';
ALTER TYPE "CardioType" ADD VALUE 'AEROBICS';
ALTER TYPE "CardioType" ADD VALUE 'ZUMBA';
ALTER TYPE "CardioType" ADD VALUE 'BROADCAST_DANCE';
ALTER TYPE "CardioType" ADD VALUE 'SPORTS_DANCE';
ALTER TYPE "CardioType" ADD VALUE 'STAIRMASTER';

-- AlterTable
ALTER TABLE "Record" ADD COLUMN "cardioDurationHours" INTEGER;
